import { box, cone, plate, tube } from '../../core/primitives';
import type { AttachmentDefinition } from '../../core/types';

/** Small weapons: a housing on the mount and barrels extending along +Z. */
export const WEAPONS: readonly AttachmentDefinition[] = [
  {
    id: 'weapon-autocannon',
    name: 'Autocannon',
    category: 'weapon',
    size: 'small',
    description: 'Long-barrelled kinetic gun.',
    stats: { mass: 3, firepower: 5 },
    primitives: [
      box({ shape: 'chamfered', chamfer: 0.12, size: [0.7, 0.6, 1.1], at: [0, 0, 0.55], role: 'dark' }),
      tube({ radius: 0.36, z: [0.9, 1.05], role: 'trim' }),
      tube({ radius: 0.09, z: [1.05, 4.3], role: 'metal' }),
      tube({ radius: 0.14, z: [4.3, 4.65], role: 'dark' }),
    ],
  },
  {
    id: 'weapon-laser',
    name: 'Laser Cannon',
    category: 'weapon',
    size: 'small',
    description: 'Focused beam emitter with a glowing lens.',
    stats: { mass: 3, firepower: 6 },
    primitives: [
      box({ shape: 'chamfered', chamfer: 0.12, size: [0.7, 0.6, 0.9], at: [0, 0, 0.45], role: 'trim' }),
      tube({ radius: 0.2, z: [0.9, 3.0], role: 'dark' }),
      tube({ radius: 0.27, z: [1.5, 1.7], role: 'metal' }),
      tube({ radius: 0.27, z: [2.2, 2.4], role: 'metal' }),
      tube({ radius: 0.15, z: [3.0, 3.3], role: 'glow' }),
    ],
  },
  {
    id: 'weapon-missile-pod',
    name: 'Missile Pod',
    category: 'weapon',
    size: 'small',
    description: 'Boxy launcher with trim-coloured warheads in the tubes.',
    stats: { mass: 5, firepower: 8 },
    primitives: [
      box({ shape: 'chamfered', chamfer: 0.1, size: [0.9, 0.7, 1.6], at: [0, 0, 0.8], role: 'dark' }),
      box({ size: [0.95, 0.1, 0.5], at: [0, 0.3, 0.5], role: 'trim' }),
      tube({ radius: 0.13, z: [1.6, 1.85], at: [0.22, 0.17, 0], role: 'trim', mirror: true }),
      tube({ radius: 0.13, z: [1.6, 1.85], at: [0.22, -0.17, 0], role: 'trim', mirror: true }),
    ],
  },
  {
    id: 'weapon-plasma',
    name: 'Plasma Repeater',
    category: 'weapon',
    size: 'small',
    description: 'Twin barrels, short and hot.',
    stats: { mass: 3, firepower: 7 },
    primitives: [
      box({ shape: 'chamfered', chamfer: 0.1, size: [0.8, 0.5, 0.8], at: [0, 0, 0.4], role: 'metal' }),
      tube({ radius: 0.1, z: [0.8, 2.9], at: [0.22, 0, 0], role: 'dark', mirror: true }),
      tube({ radius: 0.16, z: [1.0, 1.2], at: [0.22, 0, 0], role: 'trim', mirror: true }),
      tube({ radius: 0.13, z: [2.9, 3.15], at: [0.22, 0, 0], role: 'glow', mirror: true }),
    ],
  },
  {
    id: 'weapon-gauss-rifle',
    name: 'Gauss Rifle',
    category: 'weapon',
    size: 'small',
    description: 'Heavy coilgun. Slow, single slugs that hit hard.',
    stats: { mass: 5, firepower: 8 },
    primitives: [
      box({ shape: 'chamfered', chamfer: 0.12, size: [0.72, 0.62, 1.2], at: [0, 0, 0.6], role: 'dark' }),
      tube({ radius: 0.14, z: [1.2, 4.6], role: 'metal' }),
      tube({ radius: 0.27, z: [1.5, 1.72], role: 'trim' }),
      tube({ radius: 0.27, z: [2.3, 2.52], role: 'trim' }),
      tube({ radius: 0.27, z: [3.1, 3.32], role: 'trim' }),
      tube({ radius: 0.19, z: [4.6, 4.95], role: 'dark' }),
      tube({ radius: 0.1, z: [1.0, 1.2], role: 'glow' }),
    ],
  },
  {
    id: 'weapon-flak-cannon',
    name: 'Flak Cannon',
    category: 'weapon',
    size: 'small',
    description: 'Short, wide-mouthed scattergun. Shreds rocks up close.',
    stats: { mass: 4, firepower: 6 },
    primitives: [
      box({ shape: 'chamfered', chamfer: 0.12, size: [0.8, 0.62, 0.9], at: [0, 0, 0.45], role: 'metal' }),
      tube({ radius: [0.3, 0.4], z: [0.9, 2.2], role: 'dark' }),
      tube({ radius: 0.42, z: [2.05, 2.2], role: 'trim' }),
      tube({ radius: 0.34, z: [0.9, 1.05], role: 'trim' }),
    ],
  },
  {
    id: 'weapon-siege-beam',
    name: 'Siege Beam',
    category: 'weapon',
    size: 'small',
    description: 'Slow-charging heavy emitter. One long, devastating beam.',
    stats: { mass: 6, firepower: 12 },
    primitives: [
      box({ shape: 'chamfered', chamfer: 0.14, size: [0.76, 0.66, 1.3], at: [0, 0, 0.65], role: 'dark' }),
      tube({ radius: 0.28, z: [1.3, 2.6], role: 'trim' }),
      plate({ size: [1.1, 0.5], at: [0.3, 0, 1.9], facing: 'x', role: 'metal', mirror: true }),
      plate({ size: [1.1, 0.5], at: [0, 0.3, 1.9], facing: 'y', role: 'metal' }),
      tube({ radius: 0.36, z: [2.3, 2.46], role: 'metal' }),
      tube({ radius: 0.2, z: [2.6, 2.95], role: 'glow' }),
    ],
  },
  {
    id: 'weapon-arc-caster',
    name: 'Arc Caster',
    category: 'weapon',
    size: 'small',
    description: 'Twin prongs that throw a crackling short-range arc.',
    stats: { mass: 3, firepower: 7 },
    primitives: [
      box({ shape: 'chamfered', chamfer: 0.12, size: [0.72, 0.6, 0.8], at: [0, 0, 0.4], role: 'dark' }),
      tube({ radius: 0.08, z: [0.8, 2.6], at: [0.24, 0, 0], role: 'metal', mirror: true }),
      cone({ radius: 0.1, z: [2.6, 2.9], at: [0.24, 0, 0], role: 'trim', mirror: true }),
      tube({ radius: 0.16, z: [1.0, 1.25], role: 'glow' }),
      box({ size: [0.6, 0.12, 0.3], at: [0, 0.3, 0.9], role: 'trim' }),
    ],
  },
  {
    id: 'weapon-rocket-pod',
    name: 'Rocket Pod',
    category: 'weapon',
    size: 'small',
    description: 'Six-tube pod firing fast unguided rockets in bursts of three.',
    stats: { mass: 5, firepower: 9 },
    primitives: [
      box({ shape: 'chamfered', chamfer: 0.1, size: [0.9, 0.7, 1.5], at: [0, 0, 0.75], role: 'metal' }),
      tube({ radius: 0.1, z: [1.5, 1.72], at: [0.26, 0.17, 0], role: 'dark', mirror: true }),
      tube({ radius: 0.1, z: [1.5, 1.72], at: [0.26, -0.17, 0], role: 'dark', mirror: true }),
      tube({ radius: 0.1, z: [1.5, 1.72], at: [0, 0.17, 0], role: 'dark' }),
      tube({ radius: 0.1, z: [1.5, 1.72], at: [0, -0.17, 0], role: 'dark' }),
      box({ size: [0.95, 0.1, 0.4], at: [0, 0.3, 0.4], role: 'trim' }),
    ],
  },
  {
    id: 'weapon-seeker-missiles',
    name: 'Seeker Missiles',
    category: 'weapon',
    size: 'small',
    description: 'Twin rail of homing missiles. Slow but relentless.',
    stats: { mass: 5, firepower: 11 },
    primitives: [
      box({ shape: 'chamfered', chamfer: 0.08, size: [0.9, 0.5, 1.4], at: [0, 0.05, 0.7], role: 'dark' }),
      tube({ radius: 0.14, z: [0.3, 1.9], at: [0.26, -0.2, 0], role: 'metal', mirror: true }),
      cone({ radius: 0.14, z: [1.9, 2.3], at: [0.26, -0.2, 0], role: 'trim', mirror: true }),
      plate({ size: [0.5, 0.3], at: [0.26, -0.2, 0.55], facing: 'x', role: 'trim', mirror: true }),
      box({ size: [0.95, 0.1, 0.4], at: [0, 0.32, 0.5], role: 'trim' }),
    ],
  },
  {
    id: 'weapon-point-defence',
    name: 'Point Defence Turret',
    category: 'weapon',
    size: 'small',
    description: 'Compact twin-barrel turret for haulers.',
    stats: { mass: 2, firepower: 3 },
    primitives: [
      tube({ radius: 0.4, z: [0, 0.45], role: 'dark' }),
      box({ shape: 'chamfered', chamfer: 0.08, size: [0.55, 0.4, 0.6], at: [0, 0.05, 0.75], role: 'metal' }),
      tube({ radius: 0.06, z: [1.05, 2.2], at: [0.14, 0.05, 0], role: 'metal', mirror: true }),
      box({ size: [0.2, 0.1, 0.3], at: [0, 0.3, 0.75], role: 'trim' }),
    ],
  },
];
