import { SRGBColorSpace, Texture, TextureLoader } from 'three';

/**
 * Background art for flight mode. Everything here is a PNG under
 * public/assets/space (generated by tools/generate-space-assets.py; swap in
 * your own files with the same names). Planets are rendered as billboard
 * sprites, so the backdrop stays flat 2D regardless of camera tilt.
 */

export type PlanetKind = 'gas' | 'rock' | 'ice' | 'lava' | 'moon';

export interface PlanetArt {
  readonly file: string;
  readonly kind: PlanetKind;
  /** Fraction of the image width taken up by the planet disc; the sprite is scaled to compensate. */
  readonly discFraction: number;
}

export const PLANET_ART: readonly PlanetArt[] = [
  { file: 'planet-gas-01.png', kind: 'gas', discFraction: 0.84 },
  { file: 'planet-gas-02.png', kind: 'gas', discFraction: 0.84 },
  { file: 'planet-rock-01.png', kind: 'rock', discFraction: 0.84 },
  { file: 'planet-rock-02.png', kind: 'rock', discFraction: 0.84 },
  { file: 'planet-ice-01.png', kind: 'ice', discFraction: 0.84 },
  { file: 'planet-lava-01.png', kind: 'lava', discFraction: 0.84 },
];

export const MOON_ART: readonly PlanetArt[] = [
  { file: 'moon-01.png', kind: 'moon', discFraction: 0.88 },
  { file: 'moon-02.png', kind: 'moon', discFraction: 0.88 },
];

export const NEBULA_FILES: readonly string[] = ['nebula-01.png', 'nebula-02.png', 'nebula-03.png'];
export const STAR_SPRITE_FILE = 'star.png';
export const SUN_SPRITE_FILE = 'sun.png';

interface CachedTexture {
  texture: Texture;
  loaded: boolean;
  readonly callbacks: Array<() => void>;
}

const cache = new Map<string, CachedTexture>();
const loader = new TextureLoader();

/** Resolve a file under the public asset folder, honouring Vite's base URL. */
export function spaceAssetUrl(file: string): string {
  return `${import.meta.env.BASE_URL}assets/space/${file}`;
}

/**
 * Texture for a space asset, cached per file. The texture object is returned
 * immediately and fills in when the PNG arrives; `onLoad` fires then (or at
 * once if it is already loaded).
 */
export function spaceTexture(file: string, onLoad?: () => void): Texture {
  let entry = cache.get(file);
  if (!entry) {
    const created: CachedTexture = { texture: new Texture(), loaded: false, callbacks: [] };
    created.texture = loader.load(spaceAssetUrl(file), () => {
      created.loaded = true;
      for (const callback of created.callbacks.splice(0)) callback();
    }) as Texture;
    created.texture.colorSpace = SRGBColorSpace;
    cache.set(file, created);
    entry = created;
  }
  if (onLoad) {
    if (entry.loaded) onLoad();
    else entry.callbacks.push(onLoad);
  }
  return entry.texture;
}
